service: vu-amplify-lambda-basic-ops

frameworkVersion: "3"

package:
  exclude:
    - node_modules/**
    - venv/**

plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-prune-plugin

custom:
  pythonRequirements:
    dockerizePip: true
  stageVariables: ${file(../var/${self:provider.stage}-var.yml)} 
  stages:
    - dev
    - staging
    - prod

    
provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  versionFunctions: false
  environment:
    OAUTH_AUDIENCE: ${self:custom.stageVariables.OAUTH_AUDIENCE}
    OAUTH_ISSUER_BASE_URL: ${self:custom.stageVariables.OAUTH_ISSUER_BASE_URL}
    CHAT_ENDPOINT: "http://localhost:8000" #${self:custom.stageVariables.CHAT_ENDPOINT}
    DEFAULT_SECRET_PARAMETER_PREFIX: "/pdb"
    DEFAULT_ACCOUNT: "default"
    DEFAULT_LLM_QUERY_MODEL: "anthropic.claude-3-5-sonnet-20240620-v1:0"
    OBJECT_ACCESS_API_ENDPOINT: ${self:custom.stageVariables.OBJECT_ACCESS_PERMISSIONS_ENDPOINT}

  apiGateway:
    restApiId:
      ${self:custom.stageVariables.REST_API_ID}
    restApiRootResourceId:
      ${self:custom.stageVariables.REST_API_ROOT_RESOURCE_ID}

functions:

  llm_prompt_datasource:
    handler: service/core.llm_prompt_datasource
    timeout: 30
    events:
      - http:
          path: llm/query
          method: post
          cors: true

  llm_qa_check:
    handler: service/core.llm_qa_check
    timeout: 30
    events:
      - http:
            path: /llm/qa_check
            method: post
            cors: true
